### ISSUE TITLE
Remove __toString() from StreamInterface and URIInterface?

### ISSUE THREAD

**Issue by fredemmott** [facebookexperimental/hack-http-request-response-interfaces#10]
Support for implicit coercions seems unnecessary.

**Comment by usox** [comment]
- StreamInterface: Remove it. It's possible to retrieve the complete stream by getContents which will also throw Exceptions.
- UriInterface: It should be replaced by a non-magic method to retrieve the full uri.

**Comment by fredemmott** [comment]
This is still in a few places, need to check before releasing.
