### ISSUE TITLE
StreamInterface::getMetadata() is untyped

### ISSUE THREAD

**Issue by fredemmott** [facebookexperimental/hack-http-request-response-interfaces#11]
The type depends on whether a key was provided. Options include:

 - never taking a key
 - splitting it to two functions - one returning a dict, one returning mixed

This matters more for Hack as Hack dissallows indexing mixed values.

**Comment by usox** [comment]
Dropping the key and returning an `ImmMap<string, mixed>` sounds good to me...

**Comment by fredemmott** [comment]
We're definitely moving away from the collection objects; this would be `dict<string, mixed>`: https://docs.hhvm.com/hack/collections/hack-arrays

**Comment by usox** [comment]
Fixed by #17
