### ISSUE TITLE
URIInterface: type mismatch between getUserInfo() and withUserInfo()

### ISSUE THREAD

**Issue by fredemmott** [facebookexperimental/hack-http-request-response-interfaces#13]
- `withUserInfo()` takes `string $user, ?string $password`
- `getUserInfo()` always returns `string`

Options include:
 - making `getUserInfo()` return `?(string, ?string)`
 - making `getUserInfo()` return `?shape('user' => string, 'pass' => ?string)`
 - separate getters for user and password (inconsistent with everything else, but nice for typing)

**Comment by usox** [comment]
Well, as I like those single method solutions like withUserInfo and getUserInfo, I'm ok with a shape as return value.
