### ISSUE TITLE
RequestInterface: getRequestTarget() and withRequestTarget() are untyped

### ISSUE THREAD

**Issue by fredemmott** [facebookexperimental/hack-http-request-response-interfaces#2]
- `getRequestTarget()` is documented as returning a string, however this isn't the case if `withRequestTarget()` is called, which explicitly allows an implementation-defined object.

Options include:
 - make it a generic
 - only allow strings; implementations can add an additional method that isn't in the interface if they wish

**Comment by usox** [comment]
+1 for strings. Implementations should handle this if they like to...
