### ISSUE TITLE
Abstract away `resource` (streams)

### ISSUE THREAD

**Issue by fredemmott** [facebookexperimental/hack-http-request-response-interfaces#25]
resources are not type-safe and are a PHPIsm. Some options are:

1. add support for directly using strings
2. omit support for now
3. use HH\Lib\Experimental\IO\Handle (https://github.com/hhvm/hsl-experimental)

My instinct would be both (1) and (3)

**Comment by usox** [comment]
I will try 3 (+1), I am already using hsl-experimental for filesystem related things in UploadedFile.

**Comment by fredemmott** [comment]
b83a106

**Comment by fredemmott** [comment]
5baf46d6682a02331c533ec72782385a12bb7aa2
