### ISSUE TITLE
Re-evalualate nullable stuff in URIs

### ISSUE THREAD

**Issue by fredemmott** [facebookexperimental/hack-http-request-response-interfaces#26]
cc @usox 

I don't think we should return `?string` where there is not an observerable difference between `not provided` and `empty` when using HTTP, or in the string representation of URIs

For example, `getRawQuery()` - does `"/foo"` have a different rawquery to `"/foo?"`? Is the answer the same if we're looking at the current URI and it was a request to one of those?

**Comment by usox** [comment]
Related to #12

**Comment by usox** [comment]
I'm ok with that. My main goal in changing the return values to support `null` was to align the interface methods. Imho all getters should work the same way
